<?php

namespace App\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function allusers()
    {

        $qb = $this->createQueryBuilder("u");


        $qb->select('u');


        return $qb ->getQuery()->getArrayResult();

    }

}